apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-client-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-client-app
  template:
    metadata:
      labels:
        app: log-client-app
    spec:
      containers:
      - image: log-client-kubernetes-app:latest
        name: container1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"